all: mesh0 mesh1 mesh2 mesh3 mesh4 mesh5 mesh6 mesh7 mesh8 mesh9 mesh10 mesh11 mesh12 mesh13 mesh14

mesh0:
	gmsh -3 -format msh2 -clscale 0.2 bfs_geometry.geo -algo meshadapt -o bfs_3d_0.msh -format msh2
mesh1:
	gmsh -3 -format msh2 -clscale 0.19 bfs_geometry.geo -algo meshadapt -o bfs_3d_1.msh -format msh2
mesh2:
	gmsh -3 -format msh2 -clscale 0.18 bfs_geometry.geo -algo meshadapt -o bfs_3d_2.msh -format msh2
mesh3:
	gmsh -3 -format msh2 -clscale 0.17 bfs_geometry.geo -algo meshadapt -o bfs_3d_3.msh -format msh2
mesh4:
	gmsh -3 -format msh2 -clscale 0.16 bfs_geometry.geo -algo meshadapt -o bfs_3d_4.msh -format msh2
mesh5:
	gmsh -3 -format msh2 -clscale 0.15 bfs_geometry.geo -algo meshadapt -o bfs_3d_5.msh -format msh2
mesh6:
	gmsh -3 -format msh2 -clscale 0.14 bfs_geometry.geo -algo meshadapt -o bfs_3d_6.msh -format msh2
mesh7:
	gmsh -3 -format msh2 -clscale 0.13 bfs_geometry.geo -algo meshadapt -o bfs_3d_7.msh -format msh2
mesh8:
	gmsh -3 -format msh2 -clscale 0.12 bfs_geometry.geo -algo meshadapt -o bfs_3d_8.msh -format msh2
mesh9:
	gmsh -3 -format msh2 -clscale 0.11 bfs_geometry.geo -algo meshadapt -o bfs_3d_9.msh -format msh2
mesh10:
	gmsh -3 -format msh2 -clscale 0.01 bfs_geometry.geo -algo meshadapt -o bfs_3d_10.msh -format msh2
mesh11:
	gmsh -3 -format msh2 -clscale 0.09 bfs_geometry.geo -algo meshadapt -o bfs_3d_10.msh -format msh2
mesh12:
	gmsh -3 -format msh2 -clscale 0.08 bfs_geometry.geo -algo meshadapt -o bfs_3d_10.msh -format msh2
mesh13:
	gmsh -3 -format msh2 -clscale 0.07 bfs_geometry.geo -algo meshadapt -o bfs_3d_10.msh -format msh2
mesh14:
	gmsh -3 -format msh2 -clscale 0.06 bfs_geometry.geo -algo meshadapt -o bfs_3d_10.msh -format msh2
