all: mesh0 mesh1 mesh2 mesh3 mesh4 mesh5 mesh6 mesh7 mesh8 mesh9 mesh10 mesh11 mesh12 mesh13 mesh14

mesh0:
	gmsh -2 -format msh2 -clscale 0.1 bfs_geometry.geo -algo meshadapt -o bfs_2d_0.msh -format msh2
mesh1:
	gmsh -2 -format msh2 -clscale 0.09 bfs_geometry.geo -algo meshadapt -o bfs_2d_1.msh -format msh2
mesh2:
	gmsh -2 -format msh2 -clscale 0.08 bfs_geometry.geo -algo meshadapt -o bfs_2d_2.msh -format msh2
mesh3:
	gmsh -2 -format msh2 -clscale 0.07 bfs_geometry.geo -algo meshadapt -o bfs_2d_3.msh -format msh2
mesh4:
	gmsh -2 -format msh2 -clscale 0.06 bfs_geometry.geo -algo meshadapt -o bfs_2d_4.msh -format msh2
mesh5:
	gmsh -2 -format msh2 -clscale 0.05 bfs_geometry.geo -algo meshadapt -o bfs_2d_5.msh -format msh2
mesh6:
	gmsh -2 -format msh2 -clscale 0.04 bfs_geometry.geo -algo meshadapt -o bfs_2d_6.msh -format msh2
mesh7:
	gmsh -2 -format msh2 -clscale 0.03 bfs_geometry.geo -algo meshadapt -o bfs_2d_7.msh -format msh2
mesh8:
	gmsh -2 -format msh2 -clscale 0.02 bfs_geometry.geo -algo meshadapt -o bfs_2d_8.msh -format msh2
mesh9:
	gmsh -2 -format msh2 -clscale 0.01 bfs_geometry.geo -algo meshadapt -o bfs_2d_9.msh -format msh2
mesh10:
	gmsh -2 -format msh2 -clscale 0.009 bfs_geometry.geo -algo meshadapt -o bfs_2d_10.msh -format msh2
mesh11:
	gmsh -2 -format msh2 -clscale 0.008 bfs_geometry.geo -algo meshadapt -o bfs_2d_11.msh -format msh2
mesh12:
	gmsh -2 -format msh2 -clscale 0.007 bfs_geometry.geo -algo meshadapt -o bfs_2d_12.msh -format msh2
mesh13:
	gmsh -2 -format msh2 -clscale 0.006 bfs_geometry.geo -algo meshadapt -o bfs_2d_13.msh -format msh2
mesh14:
	gmsh -2 -format msh2 -clscale 0.005 bfs_geometry.geo -algo meshadapt -o bfs_2d_14.msh -format msh2
