#!/bin/bash

# This script was used to produce the results in the paper.

# Running Maxwell examples
python Maxwell/Maxwell.py -N 10 -Re 100; sleep 10

# Running Stokes examples
python Stokes/Stokes_ldc.py -N 10 -Re 1000; sleep 10


# Running Navier-Stokes examples

# 2D
python NavierStokes/NavierStokes_ldc.py -N 10 -Re 1; sleep 10
python NavierStokes/NavierStokes_ldc.py -N 10 -Re 100; sleep 10

python NavierStokes/NavierStokes_bfs.py -N 10 -Re 10; sleep 10

# 3D
python NavierStokes/NavierStokes_ldc.py -N 6 -Re 100 --space-dim 3D; sleep 10
